### ISSUE TITLE
Request of feature

### ISSUE THREAD

**Issue by Piero87** [honcheng/PaperFold-for-iOS#1]
Hello, this project is awesome! really you make a great work! i want suggest you a feature, i don't know if it's possible, but i want know if is possible to add this feature, if the middle view is a uitableview, scrolling right to left open the paper fold view, but disable the apple method to delete a row in the table view with the swipe on the row, so i want know if it's possible add the feature that don't disable this right to left swipe for table view, and for open the paper fold need to click on a row on a table view, and to close the paper fold as is now. what you think?

Thanks!

**Comment by honcheng** [comment]
Sure, this will be in my todo, unless you've added it and send a pull request :p

**Comment by Piero87** [comment]
Great! no i haven't added it, I do not know where to start :(

i hope you add it soon! :D

**Comment by honcheng** [comment]
Done. Feel free to send me pull requests if you have any improvements. 

Thanks
