### ISSUE TITLE
Delegate firing intermittently

### ISSUE THREAD

**Issue by davypaperboy** [honcheng/PaperFold-for-iOS#14]
I'm using the delegate change state method on a small (66 point wide) left view, attempting to lock a tableview from scrolling when the left view is open.

it only seems to be called when the view moves into the closed state, however I am getting callbacks on opened state, but these are infrequent. 

I've looked at your delegate methods and can't see any initial problems with what I want to do.

BTW - the view is beautiful otherwise!

**Comment by honcheng** [comment]
I think this should be fixed now, but you have to check that out in the top fold branch. Can you confirm?
