### ISSUE TITLE
CocoaPods integration

### ISSUE THREAD

**Issue by evfemist** [honcheng/PaperFold-for-iOS#15]
Would be cool to have PaperFold available by the cocoaPods

**Comment by honcheng** [comment]
I'll try to figure that out

**Comment by honcheng** [comment]
I'm not sure how to add this. Can someone help and send me a pull request?

**Comment by evfemist** [comment]
found this tutorial
http://nsscreencast.com/episodes/28-creating-a-cocoapod
when I will have free time - I will do this

**Comment by texastoland** [comment]
I've [implemented](https://gist.github.com/4265020) them and will issue a pull request to CocoaPods/Specs once I've used them a couple days.
