### ISSUE TITLE
Is it possible to slide to left or right manually?

### ISSUE THREAD

**Issue by bagusflyer** [honcheng/PaperFold-for-iOS#16]
I want to slide to left or right by touch a button instead of by gesture. Is it possible? Any suggestion? Thanks

**Comment by honcheng** [comment]
yes it is.

You can just call the method to set transition state.

**Comment by honcheng** [comment]
e.g. 
[self.paperFoldView setPaperFoldState:PaperFoldStateRightUnfolded];

and if you can also disable manual dragging 
[self.paperFoldView setEnableRightFoldDragging:NO];

These are documented in the README

**Comment by bagusflyer** [comment]
Great. Thanks

在 2012-9-16，上午12:08， honcheng 写道：
