### ISSUE TITLE
边缘锯齿和折叠角度不均问题

### ISSUE THREAD

**Issue by kejinlu** [honcheng/PaperFold-for-iOS#18]
我几个月前也在研究页面折叠的相关问题。  边缘锯齿可以通过图片折叠方向的边上加一个单位的透明像素         我之前写的一个  https://github.com/kejinlu/LUFoldableView

**Comment by kejinlu** [comment]
http://geeklu.com/2012/07/ios-3d-perspective/  这是我之前研究3d透视投影时写的 呵呵

**Comment by honcheng** [comment]
I can't read Chinese, used Google transalte. Doesn't sound like these are problems.

**Comment by kejinlu** [comment]
I'm sorry. I think you can read Chinese. I mean that you can add a one-pixel transparent border around the image to enable antialiasing of the edges when rotating.

**Comment by lanxy88** [comment]
貌似是发错邮件了吧~~

发自我的 iPad

在 2012-9-21，14:31，LU notifications@github.com 写道：
