### ISSUE TITLE
UITableView scrolling does not work if table content does not exceed it's frame

### ISSUE THREAD

**Issue by malcommac** [honcheng/PaperFold-for-iOS#24]
I'm using PaperFold with a left UIView plus central UIView with an UITableView inside.
I can't scroll the table if it's content does not exceed it's frame (= there are some hidden rows you can reach with a scroll).
That's not the natural behavior of the control and even worse I can't use pull-down-to-refresh control (with UIRefreshControl of iOS6 or any other thirdy party implementation) because in fact you can scroll the table itself.
When the content exceed the frame of the table I can't scroll up (gesture is from up to down) directly but I need to scroll down and then fast scroll up again (so I can reach the hidden header of the table with the fresh control).

**Comment by malcommac** [comment]
okay solved, it was a mistake of mine sorry.

**Comment by honcheng** [comment]
Great!
