### ISSUE TITLE
Why not a - (void)setLeftFoldContentView:leftViewFoldCount:leftViewPullFactor: method?

### ISSUE THREAD

**Issue by malcommac** [honcheng/PaperFold-for-iOS#25]
The same behavior of the:
- (void)setRightFoldContentView:(UIView*)view rightViewFoldCount:(int)rightViewFoldCount rightViewPullFactor:(float)rightViewPullFactor;

with the left side.
Thanks.

**Comment by honcheng** [comment]
I have not figured out how to do multi fold on the left side yet, logic is slightly different.

**Comment by flypigz** [comment]
I hope this left-multiple-fold brach would be released soon. It would great if the left and right folding supports the same parameters. Thanks.

**Comment by honcheng** [comment]
You can try it? It's working. I have not merged it to the master branch because I'm still testing it in my own apps.
If you can help to test, that'll help to speed up the release.
Thanks.

**Comment by flypigz** [comment]
it seems that in the demo of PaperFold, when leftTableView is unFolded,  the leftTableView is not touchable (could not pull down/up the table...)... I guess that you forget to remove the screentshot when animation completed, so the leftTableView is a static image....???

**Comment by honcheng** [comment]
Try the one in top fold branch,

**Comment by honcheng** [comment]
The branch is already merged with master. Closing this thread
