### ISSUE TITLE
How to detect the fold state on touch?

### ISSUE THREAD

**Issue by paoloandrea** [honcheng/PaperFold-for-iOS#3]
How can detect if fold is open, close, ..etc.
Is possible detect it onTouch?

For example: onTouch (FoldStateTransition)

Thank you.
Great work.
p

**Comment by honcheng** [comment]
Do you mean PaperFoldState?

you'll get it in the UIViewController with self.state

typedef enum
{
    PaperFoldStateDefault = 0,
    PaperFoldStateLeftUnfolded = 1,
    PaperFoldStateRightUnfolded = 2,
    PaperFoldStateTransition = 3
} PaperFoldState;

Is this what you mean?

**Comment by paoloandrea** [comment]
But... how can i know if PaperFolderState are in trasition?
Can i use notification?
There are a delegate?

When i touch the screen and PapertFolder are in transition i need to make more action (close keyboard, ..etc.)
How can i do it?
Thank you for help me.

**Comment by honcheng** [comment]
Ah, I get what u mean now. 
It's not there yet, but I can set up delegates for this.

**Comment by paoloandrea** [comment]
Now i can use the touch event, but don't recognize  PaperFoldStateTransition
??

-(void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event {
    NSLog(@"Touch Move");
    NSLog(@"State %i",[self state]);
}
Result only 0 or 2 (slide from right to left)
;)

**Comment by honcheng** [comment]
Can you elaborate what you are trying to achieve?

Will a delegate like this work for your use?
- (void)foldView:(id)foldView didTransitionFromState:(FoldTransitionState)fromState toState:(FoldTransitionState)toState

**Comment by paoloandrea** [comment]
Yes, it's ok
;)

**Comment by honcheng** [comment]
done
