### ISSUE TITLE
any luck with IB/Storyboard for defining views?

### ISSUE THREAD

**Issue by randyarrowood** [honcheng/PaperFold-for-iOS#31]
first, love the fold control... can't wait to use it.

i'm trying to figure out how to use my existing project defined using IB/Storyboard for each view and it is crashing when trying to setRightFoldContentView.  i think it's because the view is already added as a subview.  i've tried removing from superview first, but still crashes/traps.

the exact errors are:  
<Error>: CGContextSaveGState: invalid context 0x0
<Error>: CGContextRestoreGState: invalid context 0x0
<Error>: CGContextSetBaseCTM: invalid context 0x0
CGContextSetBaseCTM: invalid context 0x0
CGContextClipToRect: invalid context 0x0

coming from MultiFoldView.m in setScreenshotImage on the CFRelease(imageRef)

**Comment by randyarrowood** [comment]
i think i got it...

I changed the AppDelegate.m to have:

```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{    
    RightViewController *rvc = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"rightViewID"];
    LeftViewController *lvc = [self.window.rootViewController.storyboard instantiateViewControllerWithIdentifier:@"leftViewID"];
    PaperFoldNavigationController *paperFoldNavController = [[PaperFoldNavigationController alloc] initWithRootViewController:self.window.rootViewController];
    [self.window setRootViewController:paperFoldNavController];

    [paperFoldNavController setLeftViewController:lvc width:150];
    [paperFoldNavController setRightViewController:rvc width:320.0 rightViewFoldCount:3 rightViewPullFactor:0.9];

    return YES;
}
```

**Comment by honcheng** [comment]
So this is working now? 
Thanks for letting me know.

**Comment by randyarrowood** [comment]
yes...  great control... thanks

**Comment by honcheng** [comment]
Thanks

**Comment by texastoland** [comment]
I subclassed nav controller to set side view controllers, view widths, and fold counts in IB interconnecting in storyboards them with custom segues. It probably wouldn't be too hard to encapsulate top and bottom folds too.

**Comment by lucalodi** [comment]
Hi,
I really cant get PaperFold to work with storyboard.
Any help or a tutorial would be great!

Thanks in advance,
Luca

**Comment by texastoland** [comment]
Which class are you using and what problem are you running into?

**Comment by lucalodi** [comment]
I have a blank project just to test and build a solid prototype before implement into my def app.
So my setup:
storyboard with 2 tab and navigation control.

Now how can I implement PaperFold to whole app and slide a view from storyboard?

**Comment by texastoland** [comment]
- Subclass `PaperFoldNavigationController`
- Add properties like `@property (nonatomic, copy, readonly) NSString *rootViewControllerID, *leftViewControllerID, *rightViewControllerID;`
- Override `-awakeFromNib` like:

``` objc
- (void)awakeFromNib {
  [super awakeFromNib];
  if (self.rootViewControllerID) {
    self.rootViewController = [self.storyboard instantiateViewControllerWithIdentifier:self.rootViewControllerID];
  }
  if (self.leftViewControllerID) {
    self.leftViewController = [self.storyboard instantiateViewControllerWithIdentifier:self.leftViewControllerID];
  }
  if (self.rightViewControllerID) {
    self.rightViewController = [self.storyboard instantiateViewControllerWithIdentifier:self.rightViewControllerID];
  }
}
```
- Give the view controllers you want to embed `Storyboard ID`s
- Add your custom `PaperFoldNavigationController` to the storyboard
- Add `User Defined Runtime Attributes` linking your `Storyboard ID`s to your custom properties

This should get you mostly working?

@honcheng Would you be interested in a PR to improve storyboard integration?

**Comment by honcheng** [comment]
Hi Jonathan,

What do you mean by PR?

**Comment by texastoland** [comment]
@honcheng Pull Request :neckbeard: I didn't know if you'd prefer to keep `PaperfoldNavigationController` simple. I also think `PaperfoldMenuController` should extend it. @lucalodi Any luck?

**Comment by rlove1221** [comment]
hello guys, having a little trouble trying to get it going into storyboard

**Comment by seanherman** [comment]
Hey guys - can anybody post up there working version of this with storyboards? I've tried countless times to get this working with my storyboards, but it just isn't working. Any help would be GREATLY appreciated! :)

**Comment by rlove1221** [comment]
Hello ,i'm still having a little trouble as well .  Would love to get some help also.

**Comment by amroelsherif** [comment]
why the content of left and right didn't appear while I see in the log that the views opened
