### ISSUE TITLE
UIImageView added not shown during transition

### ISSUE THREAD

**Issue by abiaad** [honcheng/PaperFold-for-iOS#34]
I have a left view with a tableView and and an UIImageView of shadow over all of this left view content. When I'm folding or unfolding this left view, my shadow disappears. 
I'm adding my shadow in viewDidLoad (like the tableview)

Here's a screenshot of my shadow image : http://d.pr/i/XGJ1

Is it a bug or am I doing something wrong ?

**Comment by honcheng** [comment]
Did table view disappear too? 
Which view did you add the uiimageview?

**Comment by abiaad** [comment]
No it didn't. y shadow is added to my tableview's container :

So tableView is added to the main view
Then imageview is added to the main view.

Something strange. If I launch my app and add some row in my tableview (without fold it), make a reloadData and then unfold my tableview : I have to wait the unfolding animation is over to see my new rows.

**Comment by honcheng** [comment]
Try adding it to the contentView of the leftFoldView directly.
Paperfold takes a screenshot of a certain view to fold. 
If you put your tableview and shadow view in a same parent view and set that parent view as left fold content view, it should work

**Comment by honcheng** [comment]
For the 2nd bug, did u update to the latest commit?

It does that because a screenshot is taken when you added it. Now it takes just before you unfold so it should reflect the latest state
