### ISSUE TITLE
Unfold View Blank when using ContainerViews

### ISSUE THREAD

**Issue by Sam-Spencer** [honcheng/PaperFold-for-iOS#36]
When using container views to unfold to the left or right view, everything folds and sizes properly, however the content from the UIContainerView is blank. Is there any way to use UIContainerViews or will there be an update for those in the future?

**Comment by honcheng** [comment]
this is solved?

**Comment by Sam-Spencer** [comment]
We managed to solve the problem by moving the UIContainerViews inside and behind the main PaperFoldView. There are still issues with sizing when dragging to unfold the right side (a silver / black rectangle appears over a gray background next to the view), however, we believe that is a problem on our side and not with this library.

**Comment by honcheng** [comment]
Ok. Thanks. 

I think you mean the NavDemo project right? I've renamed ContainmentView to NavDemo, because that demo doesn't use containment view. Hope you r using the latest branch. 

It's the same code though, just renamed the files.
