### ISSUE TITLE
in didSelectRowAtIndexPath how do you know left or center table tapped?

### ISSUE THREAD

**Issue by gordemota** [honcheng/PaperFold-for-iOS#4]

**Comment by honcheng** [comment]
You can just compare the table
e.g. You have leftTable & centerTable

-(void)tableView:(UITableView_)tableView didSelectRowAtIndexPath:(NSIndexPath_)indexPath
{
    if (tableView=leftTable)
    {
    }
    else if (tableView==centerTable)
    {
    }
}

**Comment by gordemota** [comment]
thanks, by the way, from the example tapping the left cell table did not initiate call to didSelectRowAtIndexPath. only center table work even after setting the delegate and set row numbers

**Comment by honcheng** [comment]
Yeah. I did not set that up. 
The sample is different from the video, but it should not be difficult to replicate that.

**Comment by gordemota** [comment]
thanks
