### ISSUE TITLE
Question about using paperfold on a UIViewController

### ISSUE THREAD

**Issue by Piero87** [honcheng/PaperFold-for-iOS#5]
i have a UIViewController with a UITableView connected with a .xib file like this:

 MyViewController.h
@interface MyViewController : UIViewController

@property (weak, nonatomic) IBOutlet UITableView *myTable;

to use paper fold i do this:
# import "PaperFoldViewController.h"

@interface MyViewController : PaperFoldViewController

@property (weak, nonatomic) IBOutlet UITableView *myTable;

then in the MyViewController.m i do this:
- (id)initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil
  {
  self = [super initWithNibName:nibNameOrNil bundle:nibBundleOrNil];
  if (self) {
      // Custom initialization
      UITableView *_leftTableView = [[UITableView alloc] initWithFrame:CGRectMake(0,0,100,[self.view bounds].size.height)];
      [_leftTableView setRowHeight:100];
      [self setLeftFoldContentView:_leftTableView];
  }
  return self;
  }

but if i try to unfold on the left don't  appear nothing, seem don't work, won't i have wrong?

**Comment by honcheng** [comment]
Hi,
I don't use interface builder, so I'm not sure if I can help you with this. What if you table view is not from IB?

**Comment by Piero87** [comment]
i have tried with no xib, and the touch to open the view work but i can see nothing, take a look at the code:

AppDelegate.m

```
 self.myView = [[MyTableViewController alloc] init];
self.navController = [[UINavigationController alloc] initWithRootViewController:self.myView];
```

MyTableViewController.h

```
 #import <UIKit/UIKit.h>
 #import "PaperFoldViewController.h"
 #import <MapKit/MapKit.h>
 @interface MyTableViewController : PaperFoldViewController <UITableViewDelegate,   UITableViewDataSource,MKMapViewDelegate>
 {

 }

 @property (nonatomic, strong) UITableView *tableView;
 @property (nonatomic, strong) NSArray *myArray;
 @property (strong, nonatomic) MKMapView *mapView;
 @end
```

MyTableViewController.m

```
 #import "MyTableViewController.h"
 #import <CoreLocation/CoreLocation.h>
 #import "UIView+Screenshot.h"

 @interface MyTableViewController ()

 @end

 @implementation MyTableViewController

 - (void)createArray {

 self.myArray = [NSArray arrayWithObjects:@"One", @"Two", @"Three", nil];
 }

 - (void)viewDidLoad
 {
[super viewDidLoad];
// Do any additional setup after loading the view.
[self createArray];

self.tableView = [[UITableView alloc] initWithFrame:CGRectMake(0, 0, [self.view bounds].size.width,[self.view bounds].size.height)];

self.tableView.delegate = self;
self.tableView.dataSource = self;

[self.contentView addSubview:self.tableView];

_mapView = [[MKMapView alloc] initWithFrame:CGRectMake(0,0,500,[self.view bounds].size.height)];
[self setRightFoldContentView:_mapView rightViewFoldCount:3 rightViewPullFactor:0.9];

 }

 - (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {

return 1;
  }

  - (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
return [self.myArray count];
 }

 - (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath
 {
static NSString *CellIdentifier = @"Cell";

UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
if (cell == nil) {
    cell = [[UITableViewCell alloc] initWithStyle:UITableViewCellStyleSubtitle reuseIdentifier:CellIdentifier];
}

cell.textLabel.text = [self.myArray objectAtIndex:indexPath.row];

return cell;
 }

 -(void) tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath{

//[tableView deselectRowAtIndexPath:indexPath animated:YES];

//NSLog(@"You pressed : %@", [NSString stringWithFormat:[tableView cellForRowAtIndexPath:indexPath].textLabel.text ]  );
 }

 - (void)viewDidUnload
 {
[super viewDidUnload];
// Release any retained subviews of the main view.
 }

 - (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
 {
return (interfaceOrientation == UIInterfaceOrientationPortrait);
}

@end
```

what is wrong?

**Comment by honcheng** [comment]
The left or the right view is empty?

**Comment by Piero87** [comment]
the table view is all blank i can't see the row or the line of the row, and i have only set the view on the right and is grey...this above is all the code...

**Comment by honcheng** [comment]
I think it's because I created the views in init, not viewDidLoad.

**Comment by Piero87** [comment]
now work, but when i build and the app start look on the right:

http://db.tt/SNfEUjkG

there is some grey space, then when i unfold then fold it all it's right...why?

**Comment by honcheng** [comment]
No that's a bug. You are using this on iPad? 
I have not tested it on iPad yet.

**Comment by Piero87** [comment]
yes i'm using it on ipad! i hope you can adjust it! :)...i hope it can work also with a UITabBarController e UINavigationController :)...it's a really great project!

**Comment by honcheng** [comment]
Hi,
I've created a branch that separated PaperFold from a UIViewController. I've also fixed the gap. 
But this branch is not compatible with the current master, so you will have to make quite a bit of changes to make it work. Separating it from a view controller actually makes it more flexible. I will merge that with the master branch soon.

**Comment by Piero87** [comment]
thank you very much!
