### ISSUE TITLE
How can I disable touch on center view when I'm showing the right fold?

### ISSUE THREAD

**Issue by johntiror** [honcheng/PaperFold-for-iOS#51]
Hi, like in the title I like to disable the touch events on the center view when I'm showing the map on the right. How can I do that?

**Comment by honcheng** [comment]
So you don't want the ability to drag the centre view back to restore it, or you have other subviews in the centre view that you want to disable?

**Comment by johntiror** [comment]
In the center view I have a table view, but I don't want to allow the user to select a cell if the map is shown. But, sure, I want to be able to drag back the center view

**Comment by honcheng** [comment]
I don't think there is a straight forward way to do this now automatically.

Easiest way I can think of, is that there is a delegate callback when the
fold state changed. You can enable/disable your table view inside the
delegate callback.
- (void)paperFoldView:(id)paperFoldView didFoldAutomatically:(BOOL)automated
  toState:(PaperFoldState)paperFoldState;

**Comment by johntiror** [comment]
Thanks, I think it's a good idea!
