### ISSUE TITLE
does bottom and/or top folding work?

### ISSUE THREAD

**Issue by travisweerts** [honcheng/PaperFold-for-iOS#54]
I can seem to get either to work? But maybe its just me?

**Comment by honcheng** [comment]
Hi Travis,

Is the demo working for you?

**Comment by travisweerts** [comment]
Yeah, thanks for responding... I actually went back and looked at that for a bit after I posted this. I figured out what I did wrong, and I forgot to close this. And thanks for showing off some amazing code!
