### ISSUE TITLE
TabBar application

### ISSUE THREAD

**Issue by rusyaha** [honcheng/PaperFold-for-iOS#8]
How I can add your project in TabBarApplication?

**Comment by cmarca** [comment]
I'm experiencing problems with PaperFold on a TabBarApplication too. 

If I use it on the first tab, it works fine but if I use it in any of the other tabs, the app crash. In fact, I wanna use it on a second level of navigation of the first tabs (same level as the song list of a playlst on the Music app of the iPhone) but in this place doesn't work either.

Can you provide us some help please?

**Comment by honcheng** [comment]
I have not used it with tabs before. What kind of crashes are you getting?

**Comment by cmarca** [comment]
The solution proposed by eliaskg solved the problem: removing the method drawRect in ShadowView.m

``` javascript
- (void) drawRect:(CGRect)rect
{
    if ([self.colorsArray count]>0)
    {
        [self.gradient setColors:self.colorsArray];
    }
}
```

**Comment by honcheng** [comment]
Cool. I've merged with his changes. Assumed you pull the changes too.
